// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTJ4PaiV5ygzlfSN5V6TZG_YitV9GiQ3A',
    appId: '1:609805118038:web:cb933f7f4a7132218869f7',
    messagingSenderId: '609805118038',
    projectId: 'ramakrishna-b4f4c',
    authDomain: 'ramakrishna-b4f4c.firebaseapp.com',
    databaseURL: 'https://ramakrishna-b4f4c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ramakrishna-b4f4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd1wMqe2DUaOof8FJAxa4dhu-wONOcK5M',
    appId: '1:609805118038:android:e025b20c6e16e3258869f7',
    messagingSenderId: '609805118038',
    projectId: 'ramakrishna-b4f4c',
    databaseURL: 'https://ramakrishna-b4f4c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ramakrishna-b4f4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcoxhkHwHU2LSqgYhE2JpylYJs8I1Yudc',
    appId: '1:609805118038:ios:908c036e76b3ca6f8869f7',
    messagingSenderId: '609805118038',
    projectId: 'ramakrishna-b4f4c',
    databaseURL: 'https://ramakrishna-b4f4c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ramakrishna-b4f4c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcoxhkHwHU2LSqgYhE2JpylYJs8I1Yudc',
    appId: '1:609805118038:ios:908c036e76b3ca6f8869f7',
    messagingSenderId: '609805118038',
    projectId: 'ramakrishna-b4f4c',
    databaseURL: 'https://ramakrishna-b4f4c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ramakrishna-b4f4c.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTJ4PaiV5ygzlfSN5V6TZG_YitV9GiQ3A',
    appId: '1:609805118038:web:da377b4b611686dc8869f7',
    messagingSenderId: '609805118038',
    projectId: 'ramakrishna-b4f4c',
    authDomain: 'ramakrishna-b4f4c.firebaseapp.com',
    databaseURL: 'https://ramakrishna-b4f4c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ramakrishna-b4f4c.firebasestorage.app',
  );
}
